name: Build

on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone CommonLibSSE-NG
        run: |
          New-Item -ItemType Directory -Force -Path extern
          git clone --depth 1 -b ng https://github.com/alandtse/CommonLibVR.git extern/CommonLibSSE-NG

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: bc71aa640f89933294f16e004b212c7fd3183eed

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x64-windows

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WallWalkSKSE
          path: build/Release/*.dll
